import pytest

mock_script_run_data = [{"name": "test_run0", "terrain": "test_data"},
                        {"name": "test_run0", "height": "test_data"},
                        {"name": "test_run1", "terrain": "test_data"},
                        {"name": "test_run1", "height": "test_data"},
                        {"name": "test_run2", "terrain": "test_data"},
                        {"name": "test_run2", "height": "test_data"},
                        {"name": "test_run3", "terrain": "test_data"},
                        {"name": "test_run3", "height": "test_data"},
                        {"name": "test_run4", "terrain": "test_data"},
                        {"name": "test_run4", "height": "test_data"},
                        {"name": "test_run5", "terrain": "test_data"},
                        {"name": "test_run5", "height": "test_data"},
                        {"name": "test_run6", "terrain": "test_data"},
                        {"name": "test_run6", "height": "test_data"},
                        {"name": "test_run7", "terrain": "test_data"},
                        {"name": "test_run7", "height": "test_data"},
                        {"name": "test_run8", "terrain": "test_data"},
                        {"name": "test_run8", "height": "test_data"},
                        {"name": "test_run9", "terrain": "test_data"},
                        {"name": "test_run9", "height": "test_data"}, ]
